security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall, который вообще не требует аутентификации
        register:
            pattern: ^/register
            security: false

        # Основной firewall для всего остального
        main:
            pattern: ^/
            provider: app_user_provider
            # anonymous: lazy (при необходимости)
            # http_basic: ~ (или другой метод аутентификации)

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/, roles: ROLE_USER }
